# -*- coding: utf-8 -*-
"""Kalbe_Clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnGiAWAR65zXCMn8izVjwIW4SEKIA0Np
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans

df = pd.read_csv('/content/drive/MyDrive/Case Study - Transaction.csv', delimiter=';')
df.head()

df.info()

df = df.astype({
    'CustomerID': 'category'
})
df.info()

df = df.groupby(['CustomerID']).agg({
    'TransactionID': 'count',
    'Qty': 'sum',
    'TotalAmount': 'sum'
})
df.info()

X1 = df[['Qty', 'TotalAmount']]
wcss = []
for n in range(1, 11):
  model1 = KMeans(n_clusters=n, init='k-means++', n_init=10, max_iter=300, tol=.0001, random_state=100).fit(X1)
  wcss.append(model1.inertia_)

print(wcss)

plt.figure(figsize=(8,3))
plt.plot(list(range(1,11)), wcss, color='royalblue', marker='o', linewidth=2, markersize=12, markerfacecolor='m', markeredgecolor='m')
plt.title('WCSS vs Banyaknya Cluster', fontsize=18)
plt.xlabel('Jumlah Cluster',fontsize=15)
plt.ylabel('WCSS',fontsize=15)
plt.show()

model1 = KMeans(n_clusters=3, init='k-means++', n_init=10, max_iter=300, tol=.0001, random_state=100).fit(X1)
label1 = model1.labels_
centroids1= model1.cluster_centers_
print(label1)
print(centroids1)

plt.figure(figsize=(11,6))
sns.set_style('white')
plt.scatter(x='Qty', y='TotalAmount', data=df, c=label1, cmap='winter')
plt.scatter(x= centroids1[:,0], y=centroids1[:,1], s=300, c='red')
plt.xlabel('Jumlah Pembelian', fontsize=15)
plt.ylabel('Total Pembelian', fontsize=15)
plt.title('Segmentasi Pelanggan bedasarkan Jumlah Pembelian dan Total Pembeliannya', fontsize=18)
plt.show()